name: "Bug-char-10"

on:
  workflow_dispatch:

jobs:
  poc:
    name: "poc"
    runs-on: "windows-2022"

    steps:
      - name: set env
        run: |
          echo "TEST_ENV=hello$(69 -as [char])injected=it worked" >> $env:GITHUB_ENV
          cat $env:GITHUB_ENV
      - name: check env
        run: |
          echo $env:TEST_ENV
          echo $env:injected
